baseURL = 'https://say.unco.re/'
languageCode = 'en-us'
title = 'say.unco.re'
theme = 'photophobia'

DefaultContentLanguage = 'en'
SectionPagesMenu = 'main'
pagination.pagerSize = 3
#googleAnalytics = ""

[sitemap]
changefreq = 'daily'
priority = 0.5
filename = 'sitemap.xml'

#params:
#  favicon: null
#  site_logo: null
#  description: Pellentesque commodo dolor leo.
#  recent_posts_number: 10

[markup.highlight]
style = 'nord'
