baseURL = 'https://say.unco.re/'
languageCode = 'en-us'
title = 'SAY:UNCO:RE'
theme = 'hermit-v2'

defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true

# enableGitInfo = true

pygmentsCodefences = true
pygmentsUseClasses = true

#rssLimit = 10

copyright = "Use at your liking"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

#[params.author]
#name = "CHANGE SITE AUTHOR"
#about = "CHANGE SITE AUTHOR ABOUT"

[blackfriday]
hrefTargetBlank = true
noreferrerLinks = true
nofollowLinks = true

[taxonomies]
tag = "tags"
category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
# description = "CHANGE ME SITE DESCRIPTION"
# images = [""]
themeColor = "#494f5c"
accentColor = "#018472"

#homeSubtitle = "CHANGE ME HOME SUBTITLE"
# footerCopyright = "CHANGE ME FOOTER COPYRIGHT"
# footerHideThemeName = false
# bgImg = ""
# gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

justifyContent = true

relatedPosts = false
code_copy_button = true

homeSubtitlePrinter = false
scrollToTop = true
global_mathjax = false
readTime = false
# readTimeSeparator = "CHANGE ME READ TIME"
# legacyLayout = false
shareSocial = false
# googleTagManager = "GTM-XXXXXXXX"
tagSymbol = "#"
categorySymbol = "⊲"
pinned = "Pinned Posts"
# pinnedSVGname = "pin"
listLayout = ["description", "tags", "categories", "legacy"]
# initialPublish = "Initally Posted on: "
# human = ["single", "posts"]
# noIndex = false
# denyRobots = "noindex, nofollow, noarchive"
# allowRobots = "index, follow"
# siteNoIndex = false
# noIndexPages = ["404 Page not found"]
usesAnimation = false
# mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
# mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
# [params.gallery]
# enable = true
# thumbnail = '300'

[params.dateform]
LongDate = "Jan 2, 2006"
ShortDate = "Jan 2"
NumDateShort = "2006-01-02"
NumDateLong = "2006-01-02 15:04 -0700"

# [[params.socialLinks]]
# name = "mastodon"
# url = "https://joinmastodon.org/"
#
# [[params.socialLinks]]
# name = "x"
# url = "https://twitter.com/"
#
# [[params.socialLinks]]
# name = "github"
# url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

[menu]

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 20
